### ISSUE TITLE
Yor no longer works git exit code 128

### ISSUE THREAD

**Issue by toast-gear** [bridgecrewio/yor-action#13]
Yor is constantly failing since the change to a native TypeScript action (obviously worked great pre-typescript). Logs below:

```
/usr/bin/git status -s --untracked-files=no
 M bar.tf
 M foo.tf
Yor made changes, committing
/usr/bin/git add .
/usr/bin/git -c user.name=actions@github.com -c user.email=GitHub Actions commit -m Update tags (by Yor) --author=github-actions[bot] <42212132+github-actions[bot]@users.noreply.github.com>
[detached HEAD 4f633b3] Update tags (by Yor)
 Author: github-actions[bot] <42212132+github-actions[bot]@users.noreply.github.com>
 2 files changed, 5 insertions(+), 1 deletion(-)
Changes committed, pushing...
/usr/bin/git push origin
fatal: You are not currently on a branch.
To push the history leading to the current (detached HEAD)
state now, use

    git push origin HEAD:<name-of-remote-branch>


/actions-runner/_work/_actions/bridgecrewio/yor-action/main/webpack:/yor-action/node_modules/@actions/exec/lib/toolrunner.js:592
                error = new Error(`The process '${this.toolPath}' failed with exit code ${this.processExitCode}`);
^
Error: The process '/usr/bin/git' failed with exit code 128
    at ExecState._setResult (/actions-runner/_work/_actions/bridgecrewio/yor-action/main/webpack:/yor-action/node_modules/@actions/exec/lib/toolrunner.js:592:1)
    at ExecState.CheckComplete (/actions-runner/_work/_actions/bridgecrewio/yor-action/main/webpack:/yor-action/node_modules/@actions/exec/lib/toolrunner.js:575:1)
    at ChildProcess.<anonymous> (/actions-runner/_work/_actions/bridgecrewio/yor-action/main/webpack:/yor-action/node_modules/@actions/exec/lib/toolrunner.js:469:1)
    at ChildProcess.emit (node:events:390:28)
    at maybeClose (node:internal/child_process:1064:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
```

Workflow:

```yaml
jobs:
  yor:
    runs-on: self-hosted
    # Temporary until Yor action is fixed
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
           fetch-depth: 0
      - name: Generate tags via Yor and commit
        uses: bridgecrewio/yor-action@main
```
