### ISSUE TITLE
yor_trace showing as repo name instead of yor id

### ISSUE THREAD

**Issue by jimweller** [bridgecrewio/yor-action#328]
I have a *very* simple terraform repo that just does an aws ssm parameter. I'm using it to test some github actions.

yor tags everything correctly *except* the `yor_trace`. It always shows as the repo name, the same value as `git_repo`.

UPDATE: Maybe this is by design and I'm misunderstanding? Once you have a `yor_trace`, then that's the value until you remove it. Regardless of how you change the terraform resource. I was expecting the trace value to change ehen the resource changed. My last comment is most illustrative of the behavior I see vs. what I expected.

debug log
[yor.txt](https://github.com/bridgecrewio/yor-action/files/14275904/3_yor.txt)

github action job file
```
name: yor
on:
  push:
    branches: [ main ]
jobs:
  plan:
    name: yor
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
      - name: yor
        uses: bridgecrewio/yor-action@main
        env:
          LOG_LEVEL: DEBUG
        with:
          parsers: Terraform
          config_file: .tag_config.yml
```

tag config file
```
tag_groups:
  - name: basics
    tags:
      - name: source
        value:
          default: "yor"
  - name: cpe-tags
    tags:
      - name: Product
        value:
          default: "OnBase"
      - name: CostCenter
        value:
          default: "CC5409"
      - name: EnvironmentType
        value:
          default: "Production"
      - name: Platform
        value:
          default: "AWS Delivery"
      - name: CustomerName
        value:
          default: "Hyland Software Inc"
      - name: Owner
        value:
          default: "CPEENBL"
```
